/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
	"context"
	"net/http"
	"net/url"
)

// Linger please
var (
	_ context.Context
)

type MemoryServiceI interface {
	// Recall Recall the most relevant stored statement for a question
	//
	// @description Returns HTTP 200 in both the hit and the miss case; an empty result (found=false) is a valid answer, not an error.
	// @returns *RecallResponse
	Recall(recallRequest RecallRequest) (*RecallResponse, error)

	// Recall Recall the most relevant stored statement for a question
	//
	// @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	// @description Returns HTTP 200 in both the hit and the miss case; an empty result (found=false) is a valid answer, not an error.
	// @returns *RecallResponse
	RecallWithContext(ctx context.Context, recallRequest RecallRequest) (*RecallResponse, error)

	// Record Store a statement in memory
	//
	// @description Embeds the statement and stores it in a per-bucket managed memory index, auto-creating the index on first use.
	// @returns *RecordResponse
	Record(recordRequest RecordRequest) (*RecordResponse, error)

	// Record Store a statement in memory
	//
	// @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	// @description Embeds the statement and stores it in a per-bucket managed memory index, auto-creating the index on first use.
	// @returns *RecordResponse
	RecordWithContext(ctx context.Context, recordRequest RecordRequest) (*RecordResponse, error)
}

// MemoryService communicating with the Memory
// endpoints of the S3 Vector memory API
type MemoryService struct {
	client *ApiClient
}

// Recall Recall the most relevant stored statement for a question
//
// @description Returns HTTP 200 in both the hit and the miss case; an empty result (found=false) is a valid answer, not an error.
// @returns *RecallResponse
func (s *MemoryService) Recall(
	recallRequest RecallRequest,
) (*RecallResponse, error) {
	return s.RecallWithContext(
		context.Background(),
		recallRequest,
	)
}

// Recall Recall the most relevant stored statement for a question
//
// @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
// @description Returns HTTP 200 in both the hit and the miss case; an empty result (found=false) is a valid answer, not an error.
// @returns *RecallResponse
func (s *MemoryService) RecallWithContext(
	ctx context.Context,
	recallRequest RecallRequest,
) (*RecallResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/Recall"

	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = recallRequest
	var userJwt string

	req, err := s.client.prepareRequest(
		ctx,
		http.MethodPost,
		localVarPath,
		localVarPostBody,
		localVarQueryParams,
		userJwt,
		false,
	)
	if err != nil {
		return nil, err
	}

	res := new(RecallResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil
}

// Record Store a statement in memory
//
// @description Embeds the statement and stores it in a per-bucket managed memory index, auto-creating the index on first use.
// @returns *RecordResponse
func (s *MemoryService) Record(
	recordRequest RecordRequest,
) (*RecordResponse, error) {
	return s.RecordWithContext(
		context.Background(),
		recordRequest,
	)
}

// Record Store a statement in memory
//
// @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
// @description Embeds the statement and stores it in a per-bucket managed memory index, auto-creating the index on first use.
// @returns *RecordResponse
func (s *MemoryService) RecordWithContext(
	ctx context.Context,
	recordRequest RecordRequest,
) (*RecordResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/Record"

	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = recordRequest
	var userJwt string

	req, err := s.client.prepareRequest(
		ctx,
		http.MethodPost,
		localVarPath,
		localVarPostBody,
		localVarQueryParams,
		userJwt,
		false,
	)
	if err != nil {
		return nil, err
	}

	res := new(RecordResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil
}
