/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"reflect"
	"strconv"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/pkg/errors"
)

// ApiClient talks to the S3 Vector memory API, signing every request with
// AWS SigV4 (service "s3vectors") using a static access key / secret key
// pair. There is no login/token-exchange step -- every request is signed
// independently, matching how s3vector_gw/platform/auth verifies requests.
type ApiClient struct {
	BaseURL         *url.URL
	accessKeyID     string
	secretAccessKey string
	region          string
	httpClient      Doer

	Memory MemoryServiceI
}

type Doer interface {
	Do(*http.Request) (*http.Response, error)
}

type ApiClientOption struct {
	accessKeyID     string
	secretAccessKey string
	region          string
	baseURL         string
	httpClient      Doer
}

func (cb *ApiClientOption) BaseURL(url string) *ApiClientOption {
	cb.baseURL = url
	return cb
}

// Credentials sets the AWS-style access key ID / secret access key pair used
// to SigV4-sign every request.
func (cb *ApiClientOption) Credentials(accessKeyID, secretAccessKey string) *ApiClientOption {
	cb.accessKeyID = accessKeyID
	cb.secretAccessKey = secretAccessKey
	return cb
}

// Region sets the SigV4 region. s3vector_gw does not validate this against a
// fixed value server-side -- it re-derives the signature using whatever
// region the client signed with -- so any non-empty value both sides agree
// on works. Defaults to "us-east-1" if unset.
func (cb *ApiClientOption) Region(region string) *ApiClientOption {
	cb.region = region
	return cb
}

func (cb *ApiClientOption) HTTPClient(httpClient Doer) *ApiClientOption {
	cb.httpClient = httpClient
	return cb
}

// DefaultApiClientOptions returns the default API client options.
func DefaultApiClientOptions() *ApiClientOption {
	return &ApiClientOption{
		region:     "us-east-1",
		httpClient: http.DefaultClient,
	}
}

func NewApiClient(ctx context.Context, opts *ApiClientOption) (*ApiClient, error) {
	baseUrl, err := url.Parse(opts.baseURL)
	if err != nil {
		return nil, err
	}

	region := opts.region
	if region == "" {
		region = "us-east-1"
	}

	httpClient := opts.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	c := &ApiClient{
		BaseURL:         baseUrl,
		accessKeyID:     opts.accessKeyID,
		secretAccessKey: opts.secretAccessKey,
		region:          region,
		httpClient:      httpClient,
	}

	c.Memory = &MemoryService{client: c}

	return c, nil
}

func MustNewApiClient(ctx context.Context, opts *ApiClientOption) *ApiClient {
	c, err := NewApiClient(ctx, opts)
	if err != nil {
		panic(err)
	}
	return c
}

// signWithFixedTime is what prepareRequest calls to sign; factored out so a
// test can pin the timestamp without touching production code.
func signWithFixedTime(ctx context.Context, c *ApiClient, req *http.Request, payloadHash string, signingTime time.Time) error {
	creds := aws.Credentials{AccessKeyID: c.accessKeyID, SecretAccessKey: c.secretAccessKey}
	return v4.NewSigner().SignHTTP(ctx, creds, req, payloadHash, "s3vectors", c.region, signingTime)
}

// prepareRequest builds and AWS-SigV4-signs a request. userJwt and
// requiresSecret exist only to satisfy the call signature api.mustache's
// generated per-operation methods use -- this API has no JWT/client-secret
// auth mode, only SigV4, so both are ignored.
func (c *ApiClient) prepareRequest(
	ctx context.Context,
	method,
	urlStr string,
	body interface{},
	queryParams url.Values,
	userJwt string,
	requiresSecret bool,
) (*http.Request, error) {
	// Join urlStr (an absolute path like "/Record") onto c.BaseURL's own
	// path instead of resolving it as an RFC 3986 reference via
	// c.BaseURL.Parse: reference resolution treats an absolute-path
	// reference as replacing the base's path entirely, which would silently
	// drop any existing path component in the base URL (e.g.
	// "https://host/api" + "/Record" -> "https://host/Record" instead of
	// "https://host/api/Record"). path.Join preserves it; for a
	// bare-domain BaseURL (empty Path) this still yields exactly urlStr, so
	// path.Join("", "/Record") == "/Record" unchanged.
	u := *c.BaseURL
	u.Path = path.Join(c.BaseURL.Path, urlStr)

	query := u.Query()
	for k, v := range queryParams {
		for _, iv := range v {
			query.Add(k, iv)
		}
	}
	u.RawQuery = query.Encode()

	var bodyBytes []byte
	if body != nil {
		switch v := body.(type) {
		case *bytes.Buffer:
			bodyBytes = v.Bytes()
		default:
			encoded, err := json.Marshal(body)
			if err != nil {
				return nil, err
			}
			bodyBytes = encoded
		}
	}

	req, err := http.NewRequestWithContext(ctx, method, u.String(), bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}

	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/json")

	sum := sha256.Sum256(bodyBytes)
	payloadHash := hex.EncodeToString(sum[:])
	req.Header.Set("X-Amz-Content-Sha256", payloadHash)

	if err := signWithFixedTime(ctx, c, req, payloadHash, time.Now().UTC()); err != nil {
		return nil, errors.WithStack(err)
	}

	return req, nil
}

func (c *ApiClient) do(req *http.Request, v interface{}) (*http.Response, error) {
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if err := checkResponse(resp); err != nil {
		return nil, err
	}

	if v != nil {
		if err := json.NewDecoder(resp.Body).Decode(v); err != nil {
			return nil, err
		}
	}

	return resp, nil
}

// AgentMemoryAPIError mirrors the {__type, message} envelope every
// s3vector_gw error response body carries. Named distinctly from the
// generated APIErrorResponse model (models/model_api_error_response.go,
// produced from the OpenAPI spec's APIErrorResponse schema) to avoid a
// type redeclaration in this package.
type AgentMemoryAPIError struct {
	Type    string `json:"__type"`
	Message string `json:"message"`
}

func (e *AgentMemoryAPIError) Error() string {
	if e.Message != "" {
		return fmt.Sprintf("%s: %s", e.Type, e.Message)
	}
	return e.Type
}

func checkResponse(r *http.Response) error {
	if c := r.StatusCode; c >= 200 && c <= 299 {
		return nil
	}

	var errResp AgentMemoryAPIError
	if err := json.NewDecoder(r.Body).Decode(&errResp); err != nil {
		return errors.Wrapf(err, "s3vector sdk: call failed with status %d and an undecodable error body", r.StatusCode)
	}

	return &errResp
}

// parameterToString converts interface{} parameters to string, using a delimiter if format is provided.
func parameterToString(obj interface{}, collectionFormat string) string {
	var delimiter string

	switch collectionFormat {
	case "pipes":
		delimiter = "|"
	case "ssv":
		delimiter = " "
	case "tsv":
		delimiter = "\t"
	case "csv":
		delimiter = ","
	}

	if reflect.TypeOf(obj).Kind() == reflect.Slice {
		return strings.Trim(strings.Replace(fmt.Sprint(obj), " ", delimiter, -1), "[]")
	} else if t, ok := obj.(time.Time); ok {
		return t.Format(time.RFC3339)
	}

	return fmt.Sprintf("%v", obj)
}

// The following exist only so api.mustache's generated per-operation methods
// compile if a future spec change adds a parameter constraint that triggers
// these branches (RecordRequest/RecallRequest have none today).
func reportError(format string, a ...interface{}) error {
	return fmt.Errorf(format, a...)
}

func atoi(s string) (int, error) {
	return strconv.Atoi(s)
}

func strlen(s string) int {
	return len(s)
}

func addDeepQueryParams(obj interface{}, prefix string, params url.Values) {
}
