/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
//"encoding/json"
)

// RecallRequest struct for RecallRequest
type RecallRequest struct {
	Limit            *int32  `json:"limit,omitempty"`
	Question         *string `json:"question,omitempty"`
	ReturnDistance   *bool   `json:"returnDistance,omitempty"`
	VectorBucketName *string `json:"vectorBucketName,omitempty"`
}

// NewRecallRequest instantiates a new RecallRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecallRequest() *RecallRequest {
	this := RecallRequest{}
	return &this
}

// NewRecallRequestWithDefaults instantiates a new RecallRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecallRequestWithDefaults() *RecallRequest {
	this := RecallRequest{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *RecallRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *RecallRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *RecallRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetQuestion returns the Question field value if set, zero value otherwise.
func (o *RecallRequest) GetQuestion() string {
	if o == nil || o.Question == nil {
		var ret string
		return ret
	}
	return *o.Question
}

// GetQuestionOk returns a tuple with the Question field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetQuestionOk() (*string, bool) {
	if o == nil || o.Question == nil {
		return nil, false
	}
	return o.Question, true
}

// HasQuestion returns a boolean if a field has been set.
func (o *RecallRequest) HasQuestion() bool {
	if o != nil && o.Question != nil {
		return true
	}

	return false
}

// SetQuestion gets a reference to the given string and assigns it to the Question field.
func (o *RecallRequest) SetQuestion(v string) {
	o.Question = &v
}

// GetReturnDistance returns the ReturnDistance field value if set, zero value otherwise.
func (o *RecallRequest) GetReturnDistance() bool {
	if o == nil || o.ReturnDistance == nil {
		var ret bool
		return ret
	}
	return *o.ReturnDistance
}

// GetReturnDistanceOk returns a tuple with the ReturnDistance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetReturnDistanceOk() (*bool, bool) {
	if o == nil || o.ReturnDistance == nil {
		return nil, false
	}
	return o.ReturnDistance, true
}

// HasReturnDistance returns a boolean if a field has been set.
func (o *RecallRequest) HasReturnDistance() bool {
	if o != nil && o.ReturnDistance != nil {
		return true
	}

	return false
}

// SetReturnDistance gets a reference to the given bool and assigns it to the ReturnDistance field.
func (o *RecallRequest) SetReturnDistance(v bool) {
	o.ReturnDistance = &v
}

// GetVectorBucketName returns the VectorBucketName field value if set, zero value otherwise.
func (o *RecallRequest) GetVectorBucketName() string {
	if o == nil || o.VectorBucketName == nil {
		var ret string
		return ret
	}
	return *o.VectorBucketName
}

// GetVectorBucketNameOk returns a tuple with the VectorBucketName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallRequest) GetVectorBucketNameOk() (*string, bool) {
	if o == nil || o.VectorBucketName == nil {
		return nil, false
	}
	return o.VectorBucketName, true
}

// HasVectorBucketName returns a boolean if a field has been set.
func (o *RecallRequest) HasVectorBucketName() bool {
	if o != nil && o.VectorBucketName != nil {
		return true
	}

	return false
}

// SetVectorBucketName gets a reference to the given string and assigns it to the VectorBucketName field.
func (o *RecallRequest) SetVectorBucketName(v string) {
	o.VectorBucketName = &v
}

type NullableRecallRequest struct {
	value *RecallRequest
	isSet bool
}

func (v NullableRecallRequest) Get() *RecallRequest {
	return v.value
}

func (v *NullableRecallRequest) Set(val *RecallRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRecallRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRecallRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecallRequest(val *RecallRequest) *NullableRecallRequest {
	return &NullableRecallRequest{value: val, isSet: true}
}
