/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
//"encoding/json"
)

// APIErrorResponse struct for APIErrorResponse
type APIErrorResponse struct {
	Type    *string `json:"__type,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewAPIErrorResponse instantiates a new APIErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIErrorResponse() *APIErrorResponse {
	this := APIErrorResponse{}
	return &this
}

// NewAPIErrorResponseWithDefaults instantiates a new APIErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIErrorResponseWithDefaults() *APIErrorResponse {
	this := APIErrorResponse{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *APIErrorResponse) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIErrorResponse) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *APIErrorResponse) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *APIErrorResponse) SetType(v string) {
	o.Type = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *APIErrorResponse) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *APIErrorResponse) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *APIErrorResponse) SetMessage(v string) {
	o.Message = &v
}

type NullableAPIErrorResponse struct {
	value *APIErrorResponse
	isSet bool
}

func (v NullableAPIErrorResponse) Get() *APIErrorResponse {
	return v.value
}

func (v *NullableAPIErrorResponse) Set(val *APIErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIErrorResponse(val *APIErrorResponse) *NullableAPIErrorResponse {
	return &NullableAPIErrorResponse{value: val, isSet: true}
}
