/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
//"encoding/json"
)

// RecordResponse struct for RecordResponse
type RecordResponse struct {
	CreatedAt *int32  `json:"createdAt,omitempty"`
	MemoryId  *string `json:"memoryId,omitempty"`
}

// NewRecordResponse instantiates a new RecordResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordResponse() *RecordResponse {
	this := RecordResponse{}
	return &this
}

// NewRecordResponseWithDefaults instantiates a new RecordResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordResponseWithDefaults() *RecordResponse {
	this := RecordResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RecordResponse) GetCreatedAt() int32 {
	if o == nil || o.CreatedAt == nil {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordResponse) GetCreatedAtOk() (*int32, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RecordResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *RecordResponse) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetMemoryId returns the MemoryId field value if set, zero value otherwise.
func (o *RecordResponse) GetMemoryId() string {
	if o == nil || o.MemoryId == nil {
		var ret string
		return ret
	}
	return *o.MemoryId
}

// GetMemoryIdOk returns a tuple with the MemoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordResponse) GetMemoryIdOk() (*string, bool) {
	if o == nil || o.MemoryId == nil {
		return nil, false
	}
	return o.MemoryId, true
}

// HasMemoryId returns a boolean if a field has been set.
func (o *RecordResponse) HasMemoryId() bool {
	if o != nil && o.MemoryId != nil {
		return true
	}

	return false
}

// SetMemoryId gets a reference to the given string and assigns it to the MemoryId field.
func (o *RecordResponse) SetMemoryId(v string) {
	o.MemoryId = &v
}

type NullableRecordResponse struct {
	value *RecordResponse
	isSet bool
}

func (v NullableRecordResponse) Get() *RecordResponse {
	return v.value
}

func (v *NullableRecordResponse) Set(val *RecordResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordResponse(val *RecordResponse) *NullableRecordResponse {
	return &NullableRecordResponse{value: val, isSet: true}
}
