/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
//"encoding/json"
)

// RecallMatch struct for RecallMatch
type RecallMatch struct {
	Distance   *float32 `json:"distance,omitempty"`
	MemoryId   *string  `json:"memoryId,omitempty"`
	Similarity *float32 `json:"similarity,omitempty"`
	Statement  *string  `json:"statement,omitempty"`
}

// NewRecallMatch instantiates a new RecallMatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecallMatch() *RecallMatch {
	this := RecallMatch{}
	return &this
}

// NewRecallMatchWithDefaults instantiates a new RecallMatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecallMatchWithDefaults() *RecallMatch {
	this := RecallMatch{}
	return &this
}

// GetDistance returns the Distance field value if set, zero value otherwise.
func (o *RecallMatch) GetDistance() float32 {
	if o == nil || o.Distance == nil {
		var ret float32
		return ret
	}
	return *o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallMatch) GetDistanceOk() (*float32, bool) {
	if o == nil || o.Distance == nil {
		return nil, false
	}
	return o.Distance, true
}

// HasDistance returns a boolean if a field has been set.
func (o *RecallMatch) HasDistance() bool {
	if o != nil && o.Distance != nil {
		return true
	}

	return false
}

// SetDistance gets a reference to the given float32 and assigns it to the Distance field.
func (o *RecallMatch) SetDistance(v float32) {
	o.Distance = &v
}

// GetMemoryId returns the MemoryId field value if set, zero value otherwise.
func (o *RecallMatch) GetMemoryId() string {
	if o == nil || o.MemoryId == nil {
		var ret string
		return ret
	}
	return *o.MemoryId
}

// GetMemoryIdOk returns a tuple with the MemoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallMatch) GetMemoryIdOk() (*string, bool) {
	if o == nil || o.MemoryId == nil {
		return nil, false
	}
	return o.MemoryId, true
}

// HasMemoryId returns a boolean if a field has been set.
func (o *RecallMatch) HasMemoryId() bool {
	if o != nil && o.MemoryId != nil {
		return true
	}

	return false
}

// SetMemoryId gets a reference to the given string and assigns it to the MemoryId field.
func (o *RecallMatch) SetMemoryId(v string) {
	o.MemoryId = &v
}

// GetSimilarity returns the Similarity field value if set, zero value otherwise.
func (o *RecallMatch) GetSimilarity() float32 {
	if o == nil || o.Similarity == nil {
		var ret float32
		return ret
	}
	return *o.Similarity
}

// GetSimilarityOk returns a tuple with the Similarity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallMatch) GetSimilarityOk() (*float32, bool) {
	if o == nil || o.Similarity == nil {
		return nil, false
	}
	return o.Similarity, true
}

// HasSimilarity returns a boolean if a field has been set.
func (o *RecallMatch) HasSimilarity() bool {
	if o != nil && o.Similarity != nil {
		return true
	}

	return false
}

// SetSimilarity gets a reference to the given float32 and assigns it to the Similarity field.
func (o *RecallMatch) SetSimilarity(v float32) {
	o.Similarity = &v
}

// GetStatement returns the Statement field value if set, zero value otherwise.
func (o *RecallMatch) GetStatement() string {
	if o == nil || o.Statement == nil {
		var ret string
		return ret
	}
	return *o.Statement
}

// GetStatementOk returns a tuple with the Statement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallMatch) GetStatementOk() (*string, bool) {
	if o == nil || o.Statement == nil {
		return nil, false
	}
	return o.Statement, true
}

// HasStatement returns a boolean if a field has been set.
func (o *RecallMatch) HasStatement() bool {
	if o != nil && o.Statement != nil {
		return true
	}

	return false
}

// SetStatement gets a reference to the given string and assigns it to the Statement field.
func (o *RecallMatch) SetStatement(v string) {
	o.Statement = &v
}

type NullableRecallMatch struct {
	value *RecallMatch
	isSet bool
}

func (v NullableRecallMatch) Get() *RecallMatch {
	return v.value
}

func (v *NullableRecallMatch) Set(val *RecallMatch) {
	v.value = val
	v.isSet = true
}

func (v NullableRecallMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableRecallMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecallMatch(val *RecallMatch) *NullableRecallMatch {
	return &NullableRecallMatch{value: val, isSet: true}
}
