/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
//"encoding/json"
)

// RecordRequest struct for RecordRequest
type RecordRequest struct {
	Statement        *string `json:"statement,omitempty"`
	VectorBucketName *string `json:"vectorBucketName,omitempty"`
}

// NewRecordRequest instantiates a new RecordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordRequest() *RecordRequest {
	this := RecordRequest{}
	return &this
}

// NewRecordRequestWithDefaults instantiates a new RecordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordRequestWithDefaults() *RecordRequest {
	this := RecordRequest{}
	return &this
}

// GetStatement returns the Statement field value if set, zero value otherwise.
func (o *RecordRequest) GetStatement() string {
	if o == nil || o.Statement == nil {
		var ret string
		return ret
	}
	return *o.Statement
}

// GetStatementOk returns a tuple with the Statement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordRequest) GetStatementOk() (*string, bool) {
	if o == nil || o.Statement == nil {
		return nil, false
	}
	return o.Statement, true
}

// HasStatement returns a boolean if a field has been set.
func (o *RecordRequest) HasStatement() bool {
	if o != nil && o.Statement != nil {
		return true
	}

	return false
}

// SetStatement gets a reference to the given string and assigns it to the Statement field.
func (o *RecordRequest) SetStatement(v string) {
	o.Statement = &v
}

// GetVectorBucketName returns the VectorBucketName field value if set, zero value otherwise.
func (o *RecordRequest) GetVectorBucketName() string {
	if o == nil || o.VectorBucketName == nil {
		var ret string
		return ret
	}
	return *o.VectorBucketName
}

// GetVectorBucketNameOk returns a tuple with the VectorBucketName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecordRequest) GetVectorBucketNameOk() (*string, bool) {
	if o == nil || o.VectorBucketName == nil {
		return nil, false
	}
	return o.VectorBucketName, true
}

// HasVectorBucketName returns a boolean if a field has been set.
func (o *RecordRequest) HasVectorBucketName() bool {
	if o != nil && o.VectorBucketName != nil {
		return true
	}

	return false
}

// SetVectorBucketName gets a reference to the given string and assigns it to the VectorBucketName field.
func (o *RecordRequest) SetVectorBucketName(v string) {
	o.VectorBucketName = &v
}

type NullableRecordRequest struct {
	value *RecordRequest
	isSet bool
}

func (v NullableRecordRequest) Get() *RecordRequest {
	return v.value
}

func (v *NullableRecordRequest) Set(val *RecordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordRequest(val *RecordRequest) *NullableRecordRequest {
	return &NullableRecordRequest{value: val, isSet: true}
}
