/*
 * S3 Vector Gateway Swagger
 *
 * S3 Vector memory API (Record/Recall).
 *
 * API version: 2.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superintelligencememory

import (
//"encoding/json"
)

// RecallResponse struct for RecallResponse
type RecallResponse struct {
	Found   *bool          `json:"found,omitempty"`
	Results *[]RecallMatch `json:"results,omitempty"`
}

// NewRecallResponse instantiates a new RecallResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecallResponse() *RecallResponse {
	this := RecallResponse{}
	return &this
}

// NewRecallResponseWithDefaults instantiates a new RecallResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecallResponseWithDefaults() *RecallResponse {
	this := RecallResponse{}
	return &this
}

// GetFound returns the Found field value if set, zero value otherwise.
func (o *RecallResponse) GetFound() bool {
	if o == nil || o.Found == nil {
		var ret bool
		return ret
	}
	return *o.Found
}

// GetFoundOk returns a tuple with the Found field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallResponse) GetFoundOk() (*bool, bool) {
	if o == nil || o.Found == nil {
		return nil, false
	}
	return o.Found, true
}

// HasFound returns a boolean if a field has been set.
func (o *RecallResponse) HasFound() bool {
	if o != nil && o.Found != nil {
		return true
	}

	return false
}

// SetFound gets a reference to the given bool and assigns it to the Found field.
func (o *RecallResponse) SetFound(v bool) {
	o.Found = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *RecallResponse) GetResults() []RecallMatch {
	if o == nil || o.Results == nil {
		var ret []RecallMatch
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecallResponse) GetResultsOk() (*[]RecallMatch, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *RecallResponse) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []RecallMatch and assigns it to the Results field.
func (o *RecallResponse) SetResults(v []RecallMatch) {
	o.Results = &v
}

type NullableRecallResponse struct {
	value *RecallResponse
	isSet bool
}

func (v NullableRecallResponse) Get() *RecallResponse {
	return v.value
}

func (v *NullableRecallResponse) Set(val *RecallResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecallResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecallResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecallResponse(val *RecallResponse) *NullableRecallResponse {
	return &NullableRecallResponse{value: val, isSet: true}
}
